import assert from "node:assert/strict";
import { createManagedRowAttempt, managedRowCliForegroundDigest, managedRowStableBytes, managedRowWireId, validateManagedRowIntent, verifyManagedRowAttemptNonce, type CreateManagedRowIntent, type RevokeManagedRowIntent } from "../src/managed-row-request.js";
import { epServePublishRows, managedRowRequesterGrantRows } from "../src/endpoint-grants.js";
import { credentialLifetime, permissionsFor } from "../src/provision.js";

const callerA={owner:"u_aaaaaaaaaaaaaaaaaaaaaaaaaa",actor:"manager",uid:"aaaaaaaaaaaaaaaaaaaaaaaaaa"};
const callerB={...callerA,uid:"bbbbbbbbbbbbbbbbbbbbbbbbbb"};
const create:CreateManagedRowIntent={ver:1,command:"create-managed-row",requestId:"request_aaaaaaaa",operationId:"operation_aaaaaa",space:"task84",target:{owner:"u_aaaaaaaaaaaaaaaaaaaaaaaaaa",actor:"worker",lifecycleUid:"cccccccccccccccccccccccccc"},tokenHash:"a".repeat(64),scope:["run","spawn"],allowSubscribe:["general"],allowPublish:["general"],role:"worker",parent:"u_aaaaaaaaaaaaaaaaaaaaaaaaaa.manager",label:"worker"};
const revoke:RevokeManagedRowIntent={ver:1,command:"revoke-managed-row",requestId:"request_bbbbbbbb",operationId:"operation_bbbbbb",space:"task84",target:create.target};
assert.doesNotThrow(()=>validateManagedRowIntent({...create,operationId:`manager-spawn:${create.target.lifecycleUid}`}));
assert.doesNotThrow(()=>validateManagedRowIntent({...create,operationId:`cli-foreground:${create.target.lifecycleUid}`}));
const attempt=createManagedRowAttempt(callerA,create,Buffer.alloc(16,7));
assert.equal(attempt.nonce.length,64); assert.equal(Buffer.from(attempt.nonce,"base64url").length,48);
verifyManagedRowAttemptNonce(attempt.nonce,callerA,create);
assert.throws(()=>verifyManagedRowAttemptNonce(attempt.nonce,callerB,create));
assert.throws(()=>verifyManagedRowAttemptNonce(attempt.nonce,callerA,{...create,label:"changed"}));
assert.throws(()=>verifyManagedRowAttemptNonce(attempt.nonce.slice(1),callerA,create));
assert.notDeepEqual(createManagedRowAttempt(callerA,create).nonce,createManagedRowAttempt(callerA,create).nonce);
assert.deepEqual(managedRowStableBytes(create),managedRowStableBytes({...create}));
const retryA=createManagedRowAttempt(callerA,create),retryB=createManagedRowAttempt(callerA,create);
assert.notEqual(retryA.nonce,retryB.nonce);assert.equal(managedRowWireId(retryA.intent),managedRowWireId(retryB.intent));
const changedAttemptCoordinates=createManagedRowAttempt(callerB,create,Buffer.alloc(16,8),{kind:"local-manager",instanceId:"dddddddddddddddddddddddddd",processEpoch:2});
verifyManagedRowAttemptNonce(changedAttemptCoordinates.nonce,callerB,create,changedAttemptCoordinates.authority);
assert.equal(managedRowWireId(changedAttemptCoordinates.intent),managedRowWireId(create));
for(const changed of [{...create,requestId:"request_changed_1"},{...create,operationId:"operation_changed"},{...create,target:{...create.target,actor:"other"}},{...create,tokenHash:"b".repeat(64)},{...create,scope:["run"]},{...create,allowPublish:["other"]}]) assert.notEqual(managedRowWireId(changed),managedRowWireId(create));
const cliDigest=managedRowCliForegroundDigest(create);
for(const changed of [{...create,requestId:"request_changed_1"},{...create,tokenHash:"b".repeat(64)},{...create,operationId:"operation_changed"},{...create,target:{...create.target,actor:"other"}},{...create,scope:["run"]},{...create,allowSubscribe:["other"]},{...create,allowPublish:["other"]},{...create,role:"other"},{...create,parent:`${callerA.owner}.other`},{...create,label:"other"}])
  assert.notEqual(managedRowCliForegroundDigest(changed),cliDigest);
assert.doesNotThrow(()=>validateManagedRowIntent(revoke));
assert.throws(()=>validateManagedRowIntent({...revoke,tokenHash:"a".repeat(64)}));
assert.throws(()=>validateManagedRowIntent({...create,unknown:true}));
assert.throws(()=>validateManagedRowIntent({...create,target:{...create.target,owner:"*"}}));
assert.throws(()=>validateManagedRowIntent({...create,scope:["root"]}));
assert.throws(()=>validateManagedRowIntent({...create,scope:["spawn","run"]}));
assert.throws(()=>validateManagedRowIntent({...create,allowSubscribe:["bad/channel"]}));
assert.throws(()=>validateManagedRowIntent({...create,allowPublish:["team.*"]}));
assert.throws(()=>validateManagedRowIntent({...create,role:"bad.role"}));
assert.throws(()=>validateManagedRowIntent({...create,parent:"not-a-principal"}));
assert.throws(()=>validateManagedRowIntent({...create,space:"bad space"}));
assert.throws(()=>validateManagedRowIntent({...create,requestId:"short"}));
const createGrants=managedRowRequesterGrantRows("task84",{command:create.command,caller:callerA,nonce:attempt.nonce});
const revokeGrants=managedRowRequesterGrantRows("task84",{command:revoke.command,caller:callerA,nonce:attempt.nonce,targetOwner:revoke.target.owner});
assert.equal(createGrants.publish.length,1); assert.equal(createGrants.subscribe.length,1);
assert.equal(createGrants.publish[0].endsWith(`.${attempt.nonce}`),true);
assert.equal(createGrants.subscribe[0].endsWith(`.${attempt.nonce}`),true);
assert.equal(createGrants.publish[0].includes(".ledger."),false);
assert.equal(revokeGrants.publish[0].includes(`.revoke-managed-row.ledger.${revoke.target.owner}.`),true);
assert.equal([...createGrants.publish,...createGrants.subscribe,...revokeGrants.publish,...revokeGrants.subscribe].some(row=>row.endsWith(".*")),false);
assert.equal(createGrants.publish[0],`cotal.task84.ep.one.auth.create-managed-row.${callerA.owner}.${callerA.actor}.${callerA.uid}.${attempt.nonce}`);
assert.equal(createGrants.subscribe[0],`cotal.task84.ep.reply.auth.*.*.${callerA.owner}.${callerA.actor}.${callerA.uid}.${attempt.nonce}`);
assert.throws(()=>managedRowRequesterGrantRows("task84",{command:"create-managed-row",caller:callerA,nonce:attempt.nonce,targetOwner:create.target.owner}));
assert.throws(()=>managedRowRequesterGrantRows("task84",{command:"revoke-managed-row",caller:callerA,nonce:attempt.nonce}));
assert.throws(()=>managedRowRequesterGrantRows("task84",{command:"create-managed-row",caller:callerA,nonce:"short"}));
const authSpace=managedRowRequesterGrantRows("auth",{command:"create-managed-row",caller:callerA,nonce:attempt.nonce});
assert.equal(authSpace.subscribe[0],`cotal.auth.ep.reply.auth.*.*.${callerA.owner}.${callerA.actor}.${callerA.uid}.${attempt.nonce}`);
assert.throws(()=>managedRowRequesterGrantRows("auth",{command:"create-managed-row",caller:{...callerA,generation:"a".repeat(32)} as typeof callerA,nonce:attempt.nonce}));
assert.equal([...createGrants.publish,...createGrants.subscribe].some(row=>row.includes("_INBOX")||row.includes("$JS")||row.includes(".>")),false);
const pr={owner:callerA.owner,actor:callerA.actor,connId:"conn12345",lifecycleUid:callerA.uid};
const opts={managedRowRequester:attempt};
const perms=permissionsFor("managed-row-requester","task84",pr,opts);
assert.deepEqual(perms,{pub:{allow:createGrants.publish},sub:{allow:createGrants.subscribe}});
assert.deepEqual(credentialLifetime("managed-row-requester"),{class:"one-shot",defaultTtlSeconds:300,note:"one native managed-row create/revoke attempt; literal request and exact-nonce reply only"});
const probeBefore=permissionsFor("probe","task84",pr,{});
assert.throws(()=>permissionsFor("probe","task84",pr,opts));
assert.deepEqual(permissionsFor("probe","task84",pr,{}),probeBefore);
assert.equal(JSON.stringify(probeBefore).includes("managed-row"),false);
for(const intent of [{...create,requestId:"request_changed_1"},{...create,operationId:"operation_changed"},{...create,target:{...create.target,actor:"other"}},{...create,target:{...create.target,lifecycleUid:"dddddddddddddddddddddddddd"}},{...create,allowPublish:["other"]}])
  assert.throws(()=>permissionsFor("managed-row-requester","task84",pr,{managedRowRequester:{...attempt,intent}}));
assert.throws(()=>permissionsFor("managed-row-requester","task84",pr,{managedRowRequester:{...attempt,caller:callerB}}));
assert.throws(()=>permissionsFor("managed-row-requester","other",pr,opts));
assert.throws(()=>permissionsFor("managed-row-requester","task84",{...pr,actor:"foreign"},opts));
assert.throws(()=>permissionsFor("managed-row-requester","task84",{...pr,lifecycleUid:callerB.uid},opts));
const profiles=["agent","observer","admin","supervisor","provisioner","deprovisioner","retirement-requester","lifecycle-executor","endpoint-serve-executor","operator","purger","delivery","membership-rw","probe","channel-writer","channel-purger","teardown","control-caller-privileged","control-caller-admin","deployer","goal-writer","session-caller","session-serving","session-ledger","run-driver","run-mediator","run-operator","endpoint-evictor","issuer","run-admitter","remote-manager"] as const;
const profileOpts:Record<string,unknown>={
  agent:{lifecycleUid:callerA.uid},deprovisioner:{deprovisionTarget:{principal:`${callerA.owner}.${callerA.actor}`,lifecycleUid:callerA.uid}},"retirement-requester":{retirementRequester:{...callerA,target:create.target}},"lifecycle-executor":{lifecycleExecutor:{owner:callerA.owner,actor:callerA.actor,lifecycleUid:callerA.uid,alias:"manager"}},"endpoint-serve-executor":{endpointServeExecutor:{endpoint:"manager",instanceId:callerA.uid}},"goal-writer":{goalWriter:{endpoint:"manager"}},"session-caller":{sessionCaller:{endpoint:"manager",sessionId:"session1",epoch:1}},"session-serving":{sessionServing:{endpoint:"manager",sessionId:"session1",epoch:1}},"run-driver":{runDriver:{endpoint:"manager",runId:"run1",takeoverId:"takeover1",instanceId:callerA.uid,epoch:1}},"run-mediator":{runMediator:{endpoint:"manager",runId:"run1",takeoverId:"takeover1",instanceId:callerA.uid,epoch:1}},"run-operator":{runOperator:{endpoint:"manager",takeoverId:"takeover1"}},"run-admitter":{runAdmitter:{endpoint:"manager",runId:"run1"}},"remote-manager":{remoteManager:{instanceId:callerA.uid,owner:callerA.owner,actor:`manager_${callerA.uid}`}},teardown:{lifecycleUid:callerA.uid},"control-caller-privileged":{lifecycleUid:callerA.uid},"control-caller-admin":{lifecycleUid:callerA.uid},deployer:{lifecycleUid:callerA.uid},
};
const requestSubjects=[createGrants.publish[0],revokeGrants.publish[0]];
const intersects=(pattern:string,subject:string)=>{const p=pattern.split("."),s=subject.split(".");for(let i=0;i<p.length;i++){if(p[i]===">")return i<s.length;if(i>=s.length||p[i]!=="*"&&p[i]!==s[i])return false;}return p.length===s.length;};
const census:string[]=[];
for(const profile of profiles){const censusPr=profile==="remote-manager"?{...pr,actor:`manager_${callerA.uid}`} : pr;const p=permissionsFor(profile,"task84",censusPr,(profileOpts as Record<string,Record<string,unknown>>)[profile]??{});const rows=((p as {pub?:{allow?:string[]}}).pub?.allow??[]);const hits=rows.filter(row=>requestSubjects.some(subject=>intersects(row,subject)));assert.deepEqual(hits,[],`${profile} intersects managed-row commands`);census.push(`${profile}:${rows.length}:0`);}
const serveRows=epServePublishRows("task84","manager",callerA.uid,1);assert.deepEqual(serveRows.filter(row=>requestSubjects.some(subject=>intersects(row,subject))),[]);census.push(`endpoint-serve-publish:${serveRows.length}:0`);
console.log(`TASK84 MANAGED ROW REQUESTER 47 passed, 0 failed; PROFILE CENSUS ${census.length} families, 0 intersections\n${census.join("\n")}`);
