// @ts-check
import { readFileSync } from 'node:fs';
import { defineConfig } from 'astro/config';
import starlight from '@astrojs/starlight';
import starlightLlmsTxt from 'starlight-llms-txt';

// Sidebar is generated by scripts/sync-docs.mjs (run before dev/build). Guard so a
// fresh checkout without a sync still loads.
let sidebar = [];
try {
  sidebar = JSON.parse(readFileSync(new URL('./src/generated/sidebar.json', import.meta.url), 'utf8'));
} catch {
  sidebar = [];
}

export default defineConfig({
  // The deploy origin. Drives sitemap, canonical URLs and absolute llms.txt links.
  site: 'https://docs.cotal.ai',
  integrations: [
    starlight({
      title: 'Cotal',
      description:
        'A standard wire interface for software, especially AI agents, to coordinate in real time.',
      logo: { src: './src/assets/cotal-mark.svg', alt: '' },
      social: [{ icon: 'github', label: 'GitHub', href: 'https://github.com/cotal-ai/cotal' }],
      sidebar: [...sidebar, { label: 'For agents', items: [{ label: 'Docs for agents', slug: 'docs-for-agents' }] }],
      // Advertise each page's Markdown twin in <head> (agent auto-discovery).
      components: { Head: './src/components/Head.astro' },
      plugins: [
        starlightLlmsTxt({
          projectName: 'Cotal',
          description:
            'Cotal is a standard wire interface for software, especially AI agents, to coordinate in real time. The standard is the wire contract itself (subjects, message schemas, presence/discovery conventions); libraries are thin clients over it. Transport is NATS + JetStream.',
          details:
            'Route by task: set up + run a mesh → Quickstart (`npx cotal-ai setup --yes && npx cotal-ai up --detach`, then `cotal spawn`); message peers from a session → MCP tool catalog (cotal_send / cotal_dm / cotal_anycast); declare a team → Define a team (cotal.yaml); grant channel access → Channels & permissions; build a client in another language → Build a client + the normative Spec. The Spec is the RFC-2119 wire contract and wins over every other page; the machine-readable message schema is at /cotal.schema.json (authoritative for message shapes). Pages are marked normative / informative / reference in their opening line; Roadmap content is not shipped behavior. Core primitives: endpoint, agent node, space, channel, direct message, presence, history. Delivery modes: multicast / unicast / anycast.',
          // A compact, agent-pickable subset for small context windows: drop the
          // maintainer-facing Project section.
          exclude: ['release', 'setup-internals', 'roadmap'],
        }),
      ],
    }),
  ],
});
