// @ts-check
import { readFileSync } from 'node:fs';
import { defineConfig } from 'astro/config';
import starlight from '@astrojs/starlight';
import starlightLlmsTxt from 'starlight-llms-txt';

// Sidebar is generated by scripts/sync-docs.mjs (run before dev/build). Guard so a
// fresh checkout without a sync still loads.
let sidebar = [];
try {
  sidebar = JSON.parse(readFileSync(new URL('./src/generated/sidebar.json', import.meta.url), 'utf8'));
} catch {
  sidebar = [];
}

export default defineConfig({
  // The deploy origin. Drives sitemap, canonical URLs and absolute llms.txt links.
  site: 'https://docs.cotal.ai',
  integrations: [
    starlight({
      title: 'Cotal',
      description:
        'A standard wire interface for software, especially AI agents, to coordinate in real time.',
      logo: { src: './src/assets/cotal-mark.svg', alt: '' },
      social: [{ icon: 'github', label: 'GitHub', href: 'https://github.com/cotal-ai/cotal' }],
      sidebar: [...sidebar, { label: 'For agents', items: [{ label: 'Docs for agents', slug: 'docs-for-agents' }] }],
      // Advertise each page's Markdown twin in <head> (agent auto-discovery).
      components: { Head: './src/components/Head.astro' },
      plugins: [
        starlightLlmsTxt({
          projectName: 'Cotal',
          description:
            'Cotal is a standard wire interface for software, especially AI agents, to coordinate in real time. The standard is the wire contract itself (subjects, message schemas, presence/discovery conventions); libraries are thin clients over it. Transport is NATS + JetStream.',
          // The task router. Each link is the page's raw-Markdown twin, so an agent
          // can go straight from llms.txt to clean Markdown without touching HTML.
          details: [
            'Route by task:',
            '',
            '- [Quickstart](https://docs.cotal.ai/getting-started.md): install and start a local mesh — `npx cotal-ai setup --yes && npx cotal-ai up --detach`, then `npx cotal-ai spawn --detach`; verify with `npx cotal-ai status`',
            '- [MCP tool catalog](https://docs.cotal.ai/mcp-tools.md): message peers from inside a session (`cotal_send` / `cotal_dm` / `cotal_anycast`) and spawn teammates (`cotal_spawn` / `cotal_persona`)',
            '- [Define a team](https://docs.cotal.ai/define-a-team.md): declare a team and its channels in one `cotal.yaml`, launch with `cotal up -f`',
            '- [Channels & permissions](https://docs.cotal.ai/channels-and-permissions.md): grant or audit channel access (`subscribe` / `allowSubscribe` / `allowPublish`)',
            '- [Agent files](https://docs.cotal.ai/agent-files.md): every field of a persona file (`.cotal/agents/<name>.md`)',
            '- [Watch a mesh](https://docs.cotal.ai/watch-a-mesh.md): the terminal console and the web dashboard',
            '- [Identity & auth](https://docs.cotal.ai/identity-and-auth.md): mint credentials (`cotal mint <name> --profile agent`), how enforcement works',
            '- [Build a client](https://docs.cotal.ai/build-a-client.md): implement the wire in another language, in dependency order',
            '- [Specification](https://docs.cotal.ai/spec.md): the normative RFC-2119 wire contract — where any page disagrees with it, the spec wins',
            '- [Message schema](https://docs.cotal.ai/cotal.schema.json): machine-readable JSON Schema, authoritative for message shapes',
            '',
            'Docs pages open with a status line (normative / informative / reference); Roadmap content is not shipped behavior. Core primitives: endpoint, agent node, space, channel, direct message, presence, history. Delivery modes: multicast / unicast / anycast.',
          ].join('\n'),
          // A compact, agent-pickable subset for small context windows: drop the
          // maintainer-facing Project section.
          exclude: ['release', 'setup-internals', 'roadmap'],
        }),
      ],
    }),
  ],
});
